coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        flags:
          - unittests
    patch:
      default:
        target: auto
        threshold: 2%
        flags:
          - unittests

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
